### ISSUE TITLE
Uncaught ValueError: escapeshellarg()

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_syslog#208]
```
2023/02/08 18:03:24 - ERROR PHP ERROR: Uncaught ValueError: escapeshellarg(): Argument #1 ($arg) must not contain any null bytes in /var/www/localhost/htdocs/cacti/lib/functions.php:4492 Stack trace: #0 /var/www/localhost/htdocs/cacti/lib/functions.php(4492): escapeshellarg('Feb 8 18:02:31...') #1 /var/www/localhost/htdocs/cacti/plugins/syslog/functions.php(2282): cacti_escapeshellarg('Feb 8 18:02:31...') #2 /var/www/localhost/htdocs/cacti/plugins/syslog/functions.php(1484): alert_setup_environment(Array, Array, Array, '') #3 /var/www/localhost/htdocs/cacti/plugins/syslog/functions.php(1177): syslog_process_alert(Array, 'SELECT *\n\t\t\tFRO...', Array, 0) #4 /var/www/localhost/htdocs/cacti/plugins/syslog/syslog_process.php(198): syslog_process_alerts(110) #5 {main} thrown in file: /var/www/localhost/htdocs/cacti/lib/functions.php on line: 4492
```

**Comment by TheWitness** [comment]
Should be fixed now.
